package Main;

import Material.*;
import Lectores.*;
import Prestamos.*;

/**
 * @version 1.0
 * @author Daniel Alberto Cutimbo Jibaja [3xplo1t]
 */
public class Menu_seleccion extends javax.swing.JFrame {

    public Menu_seleccion() {
        initComponents();
        //CENTRA EL FORMULARIO EN LA PANTALLA
        setLocationRelativeTo(null);
        //DESHABILITA EL BOTON DE MAXIMIZAR EL FORMULARIO O VENTANA
        setResizable(false);
        //NOMBRE DEL FORMULARIO 
        setTitle("Menu seleccion");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btn_exit = new javax.swing.JButton();
        btn_materiales = new javax.swing.JButton();
        btn_prestamos = new javax.swing.JButton();
        btn_lectores = new javax.swing.JButton();
        png_fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(153, 0, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(781, 110));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PNGs/UTP.jpg"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("mononoki Nerd Font Mono", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("BIBLIOTECA");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("mononoki Nerd Font Mono", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SISTEMA DE CONTROL");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, -1, -1));

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setBackground(new java.awt.Color(153, 0, 0));
        jPanel3.setPreferredSize(new java.awt.Dimension(575, 30));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("mononoki Nerd Font Mono", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Diseñado por: Daniel Alberto Cutimbo Jibaja");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, -1, -1));

        jPanel1.add(jPanel3, java.awt.BorderLayout.PAGE_END);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_exit.setFont(new java.awt.Font("mononoki Nerd Font Mono", 1, 36)); // NOI18N
        btn_exit.setText("CERRAR");
        btn_exit.setActionCommand("btn_Exit");
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });
        jPanel4.add(btn_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 10, 160, 40));

        btn_materiales.setFont(new java.awt.Font("mononoki Nerd Font Mono", 1, 36)); // NOI18N
        btn_materiales.setText("MATERIALES");
        btn_materiales.setActionCommand("btn_Material");
        btn_materiales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_materialesActionPerformed(evt);
            }
        });
        jPanel4.add(btn_materiales, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 235, 70));

        btn_prestamos.setFont(new java.awt.Font("mononoki Nerd Font Mono", 1, 36)); // NOI18N
        btn_prestamos.setText("PRESTAMOS");
        btn_prestamos.setActionCommand("btn_Prestamos");
        btn_prestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_prestamosActionPerformed(evt);
            }
        });
        jPanel4.add(btn_prestamos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 235, 70));

        btn_lectores.setFont(new java.awt.Font("mononoki Nerd Font Mono", 1, 36)); // NOI18N
        btn_lectores.setText("LECTORES");
        btn_lectores.setActionCommand("btn_Lectores");
        btn_lectores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lectoresActionPerformed(evt);
            }
        });
        jPanel4.add(btn_lectores, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 235, 70));

        png_fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PNGs/FondoM.png"))); // NOI18N
        jPanel4.add(png_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 780, 420));

        jPanel1.add(jPanel4, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 711, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    //BOTON SALIR
    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_exitActionPerformed
    // BUTTON MATERIALES - LLAMA AL FORMULARIO MATERIALES
    private void btn_materialesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_materialesActionPerformed
        jMateriales formulario = new jMateriales();
        formulario.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_materialesActionPerformed
    
    // BUTTON PRESTAMOS - LLAMA AL FORMULARIO PRESTAMOS
    private void btn_prestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_prestamosActionPerformed
        jPrestamos formulario1 = new jPrestamos();
        formulario1.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_prestamosActionPerformed
    
    // BUTTON LECTORES - LLAMA AL FORMULARIO LECTORES
    private void btn_lectoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lectoresActionPerformed
        jLectores formulario = new jLectores();
        formulario.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_lectoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_seleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_seleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_seleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_seleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_seleccion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_lectores;
    private javax.swing.JButton btn_materiales;
    private javax.swing.JButton btn_prestamos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel png_fondo;
    // End of variables declaration//GEN-END:variables
}
