/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Material;

import Main.*;
import java.io.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Daniel Alberto cutimbo Jibaja [3xplo1t]
 */
public class jMateriales extends javax.swing.JFrame {
    //INICIALIZA LA LISTA ENLAZADA MATERIAL
    ListaEnlazada_material Lista = new ListaEnlazada_material();

    public jMateriales() {
        initComponents();
        //CENTRA EL FORMULARIO EN LA PANTALLA
        setLocationRelativeTo(null);
        //DESHABILITA EL BOTON DE MAXIMIZAR EL FORMULARIO O VENTANA
        setResizable(false);
        //NOMBRE DEL FORMULARIO 
        setTitle("Menu Materiales");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_regresar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtF_idmaterial = new javax.swing.JTextField();
        txtF_titulo = new javax.swing.JTextField();
        txtF_npaginas = new javax.swing.JTextField();
        txtF_fechapublicacion = new javax.swing.JTextField();
        txtF_autor = new javax.swing.JTextField();
        txtF_editorial = new javax.swing.JTextField();
        txtF_tema = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtA_mostrar = new javax.swing.JTextArea();
        btn_filtrar = new javax.swing.JButton();
        cB_tiporecurso = new javax.swing.JComboBox<>();
        cB_sedebiblioteca = new javax.swing.JComboBox<>();
        btn_generar = new javax.swing.JButton();
        btn_agregar = new javax.swing.JButton();
        btn_editar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        btn_limpiar = new javax.swing.JButton();
        btn_imprimir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(153, 0, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(1114, 30));

        jLabel4.setFont(new java.awt.Font("mononoki Nerd Font Mono", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Diseñado por: Daniel Alberto Cutimbo Jibaja");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(381, 381, 381)
                .addComponent(jLabel4)
                .addContainerGap(405, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jPanel3.setBackground(new java.awt.Color(153, 0, 0));
        jPanel3.setPreferredSize(new java.awt.Dimension(1114, 90));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PNGs/UTP.jpg"))); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel3.setFont(new java.awt.Font("mononoki Nerd Font Mono", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("MENU MATERIALES");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, -1, -1));

        btn_regresar.setBackground(new java.awt.Color(204, 0, 0));
        btn_regresar.setFont(new java.awt.Font("mononoki Nerd Font Mono", 1, 14)); // NOI18N
        btn_regresar.setForeground(new java.awt.Color(255, 255, 255));
        btn_regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PNGs/SalirLogin.png"))); // NOI18N
        btn_regresar.setText("REGRESAR");
        btn_regresar.setActionCommand("btn_Regresar");
        btn_regresar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btn_regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regresarActionPerformed(evt);
            }
        });
        jPanel3.add(btn_regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 10, 170, 70));

        jPanel1.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));
        jPanel4.setPreferredSize(new java.awt.Dimension(1021, 600));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("mononoki Nerd Font Mono", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("EDITORIAL");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel6.setFont(new java.awt.Font("mononoki Nerd Font Mono", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ID MATERIAL");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel7.setFont(new java.awt.Font("mononoki Nerd Font Mono", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("TITULO");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, -1));

        jLabel8.setFont(new java.awt.Font("mononoki Nerd Font Mono", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("AUTOR");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 20, -1, -1));

        jLabel9.setFont(new java.awt.Font("mononoki Nerd Font Mono", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("TEMA");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, -1, -1));

        jLabel10.setFont(new java.awt.Font("mononoki Nerd Font Mono", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("FECHA DE PUBLICACION");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 60, -1, -1));

        jLabel11.setFont(new java.awt.Font("mononoki Nerd Font Mono", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("N° DE PAGINAS");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 20, -1, -1));

        jLabel12.setFont(new java.awt.Font("mononoki Nerd Font Mono", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("TIPO DE RECURSO");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel13.setFont(new java.awt.Font("mononoki Nerd Font Mono", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("SEDE BIBLIOTECA");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, -1, -1));
        jPanel4.add(txtF_idmaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 80, -1));
        jPanel4.add(txtF_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 410, -1));
        jPanel4.add(txtF_npaginas, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 20, 50, -1));
        jPanel4.add(txtF_fechapublicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 60, 240, -1));
        jPanel4.add(txtF_autor, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 20, 240, -1));
        jPanel4.add(txtF_editorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 240, -1));
        jPanel4.add(txtF_tema, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, 240, -1));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        txtA_mostrar.setEditable(false);
        txtA_mostrar.setColumns(10);
        txtA_mostrar.setFont(new java.awt.Font("mononoki Nerd Font Mono", 1, 14)); // NOI18N
        txtA_mostrar.setRows(5);
        jScrollPane1.setViewportView(txtA_mostrar);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 1110, 370));

        btn_filtrar.setBackground(new java.awt.Color(255, 255, 51));
        btn_filtrar.setFont(new java.awt.Font("mononoki Nerd Font Mono", 1, 12)); // NOI18N
        btn_filtrar.setForeground(new java.awt.Color(0, 0, 0));
        btn_filtrar.setText("CONSULTA / BUSCAR");
        btn_filtrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_filtrarActionPerformed(evt);
            }
        });
        jPanel4.add(btn_filtrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 140, 150, 30));

        cB_tiporecurso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...", "LIBRO", "REVISTA", "ARTICULO" }));
        jPanel4.add(cB_tiporecurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 100, -1));

        cB_sedebiblioteca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...", "LIMA", "AREQUIPA", "CHICLAYO" }));
        jPanel4.add(cB_sedebiblioteca, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, 130, -1));

        btn_generar.setFont(new java.awt.Font("mononoki Nerd Font Mono", 1, 12)); // NOI18N
        btn_generar.setForeground(new java.awt.Color(0, 0, 0));
        btn_generar.setText("GENERAR");
        btn_generar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_generarActionPerformed(evt);
            }
        });
        jPanel4.add(btn_generar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, 130, 30));

        btn_agregar.setBackground(new java.awt.Color(0, 153, 0));
        btn_agregar.setFont(new java.awt.Font("mononoki Nerd Font Mono", 1, 12)); // NOI18N
        btn_agregar.setForeground(new java.awt.Color(255, 255, 255));
        btn_agregar.setText("AGREGAR");
        btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarActionPerformed(evt);
            }
        });
        jPanel4.add(btn_agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 100, 130, 30));

        btn_editar.setBackground(new java.awt.Color(0, 0, 102));
        btn_editar.setFont(new java.awt.Font("mononoki Nerd Font Mono", 1, 12)); // NOI18N
        btn_editar.setForeground(new java.awt.Color(255, 255, 255));
        btn_editar.setText("EDITAR");
        btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarActionPerformed(evt);
            }
        });
        jPanel4.add(btn_editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 100, 130, 30));

        btn_eliminar.setBackground(new java.awt.Color(102, 0, 0));
        btn_eliminar.setFont(new java.awt.Font("mononoki Nerd Font Mono", 1, 12)); // NOI18N
        btn_eliminar.setForeground(new java.awt.Color(255, 255, 255));
        btn_eliminar.setText("ELIMINAR");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });
        jPanel4.add(btn_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 100, 130, 30));

        btn_limpiar.setFont(new java.awt.Font("mononoki Nerd Font Mono", 1, 12)); // NOI18N
        btn_limpiar.setForeground(new java.awt.Color(0, 0, 0));
        btn_limpiar.setText("LIMPIAR");
        btn_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiarActionPerformed(evt);
            }
        });
        jPanel4.add(btn_limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 560, 130, 30));

        btn_imprimir.setFont(new java.awt.Font("mononoki Nerd Font Mono", 1, 12)); // NOI18N
        btn_imprimir.setForeground(new java.awt.Color(0, 0, 0));
        btn_imprimir.setText("IMPRIMIR");
        btn_imprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_imprimirActionPerformed(evt);
            }
        });
        jPanel4.add(btn_imprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 560, 130, 30));

        jPanel1.add(jPanel4, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1130, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 735, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regresarActionPerformed
        Menu_seleccion formulario = new Menu_seleccion();
        formulario.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_regresarActionPerformed

    //FILTRA LOS MATERIALES POR SU ID
    private void btn_filtrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_filtrarActionPerformed
        int posicion = Integer.parseInt(txtF_idmaterial.getText());
        String elemento = Lista.buscarPosicion2(posicion + 1);
        if (elemento == null) {
            JOptionPane.showMessageDialog(null, "ERROR: ID no existe en la lista de Materiales");
        } else {
            JOptionPane.showMessageDialog(null, "MATERIAL ENCONTRADO:\n" + elemento.replace(";", " "));
        }
    }//GEN-LAST:event_btn_filtrarActionPerformed
    
    //BOTON GENERAR LISTA ENLAZADA DESDE EL ARCHIVO CSV
    private void btn_generarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_generarActionPerformed
        BufferedReader br = null;
        String cadena = "";
        try {
            br = new BufferedReader(new FileReader("Materiales.csv"));
            String line = br.readLine();
            int i = line.length();
            while (line != null) {
                cadena = line + "\n";
                Lista.insertarFinal(new Nodo(cadena));
                line = br.readLine();
                i++;
            }
            br.close();
        } catch (Exception e) {
            cadena = "Error leyendo: " + e;
            txtA_mostrar.setText(cadena);
        }
    }//GEN-LAST:event_btn_generarActionPerformed

    //AGREGA ELEMENTOS A LA LISTA ENLAZADA; EL ID SE ASIGNA AUTOMATICAMENTE
    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed
        int num = Lista.tamaño();
        txtF_idmaterial.setText(String.valueOf(num));
        Material objMaterial = new Material(txtF_idmaterial.getText(), txtF_titulo.getText(), txtF_autor.getText(), txtF_npaginas.getText(), txtF_editorial.getText(),
                txtF_tema.getText(), txtF_fechapublicacion.getText(), cB_tiporecurso.getSelectedItem().toString(), cB_sedebiblioteca.getSelectedItem().toString());

        String dato = txtF_idmaterial.getText() + ";" + txtF_titulo.getText() + ";" + txtF_autor.getText() + ";" + txtF_npaginas.getText() + ";" + txtF_editorial.getText()
                + ";" + txtF_tema.getText() + ";" + txtF_fechapublicacion.getText() + ";" + cB_tiporecurso.getSelectedItem() + ";" + cB_sedebiblioteca.getSelectedItem();
        Lista.insertarFinal(new Nodo(dato));
        JOptionPane.showMessageDialog(null, "AGREGADO CON EXITO\n" + dato);

        txtA_mostrar.setText(Lista.imprimirLista().replace(";", " || "));
    }//GEN-LAST:event_btn_agregarActionPerformed

    //EDITA EL ELEMENTO USANDO SU ID COMO REFERENCIA
    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarActionPerformed
        int posicion = Integer.parseInt(txtF_idmaterial.getText());
        Nodo buscar = Lista.buscarPosicion(posicion + 1);
        if (buscar == null)
            txtA_mostrar.setText(" - ID incorrecto "
                    + "\n - Asegúrese de que el ID ingresado sea válido  ");
        else {
            Lista.retirarPosicion(posicion + 1);
            String dato = txtF_idmaterial.getText() + ";" + txtF_titulo.getText() + ";" + txtF_autor.getText() + ";" + txtF_npaginas.getText() + ";" + txtF_editorial.getText()
                    + ";" + txtF_tema.getText() + ";" + txtF_fechapublicacion.getText() + ";" + cB_tiporecurso.getSelectedItem() + ";" + cB_sedebiblioteca.getSelectedItem();
            Lista.insertarPosicion(new Nodo(dato), posicion + 1);
            txtA_mostrar.setText("");
            txtA_mostrar.setText(Lista.imprimirLista().replace(";", " || "));
        }
    }//GEN-LAST:event_btn_editarActionPerformed

    //ELIMINA UN ELEMENTO DE LA LISTA TOMANDO COMO REFERENCIA SU ID
    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        int posicion = Integer.parseInt(txtF_idmaterial.getText());
        String eliminar = Lista.retirarPosicion(posicion + 1);
        if (eliminar != null) {
            JOptionPane.showMessageDialog(null, "Elemento Eliminado  ->  " + eliminar);
        } else {
            JOptionPane.showMessageDialog(null, "ERROR: Elemento no encontrado\n- Asegúrese de que el ID ingresado sea válido");
        }
        txtA_mostrar.setText("");
        txtA_mostrar.setText(Lista.imprimirLista().replace(";", " || "));
    }//GEN-LAST:event_btn_eliminarActionPerformed

    //LIMPIA LOS CAMPOS
    private void btn_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiarActionPerformed
        txtA_mostrar.setText("");
        txtF_autor.setText("");
        txtF_editorial.setText("");
        txtF_fechapublicacion.setText("");
        txtF_idmaterial.setText("");
        txtF_npaginas.setText("");
        txtF_tema.setText("");
        txtF_titulo.setText("");
        cB_sedebiblioteca.setSelectedIndex(0);
        cB_tiporecurso.setSelectedIndex(0);
    }//GEN-LAST:event_btn_limpiarActionPerformed

    //IMPRIME LA LISTA Y LOS CAMBIOS REALIZADOS (EN CASO NO SE ACTUALIZE DE FORMA AUTOMATICA)
    private void btn_imprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_imprimirActionPerformed
        txtA_mostrar.setText("");
        txtA_mostrar.setText("" + Lista.imprimirLista().replace(";", " || "));
    }//GEN-LAST:event_btn_imprimirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jMateriales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jMateriales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jMateriales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jMateriales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jMateriales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_editar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_filtrar;
    private javax.swing.JButton btn_generar;
    private javax.swing.JButton btn_imprimir;
    private javax.swing.JButton btn_limpiar;
    private javax.swing.JButton btn_regresar;
    private javax.swing.JComboBox<String> cB_sedebiblioteca;
    private javax.swing.JComboBox<String> cB_tiporecurso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtA_mostrar;
    private javax.swing.JTextField txtF_autor;
    private javax.swing.JTextField txtF_editorial;
    private javax.swing.JTextField txtF_fechapublicacion;
    private javax.swing.JTextField txtF_idmaterial;
    private javax.swing.JTextField txtF_npaginas;
    private javax.swing.JTextField txtF_tema;
    private javax.swing.JTextField txtF_titulo;
    // End of variables declaration//GEN-END:variables
}
